name: Deploy to Render

# Run the workflow on every push to the main branch.
on:
  push:
    branches: [develop]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository.
      - name: Checkout
        uses: actions/checkout@v2

      ### ⬇ IMPORTANT PART ⬇ ###
      - name: Build, Push, and Deploy Docker Container to Render # Custom step name
        uses: gonuit/heroku-docker-deploy@v1.3.3 # Replacing Heroku step with Render commands
        with:
          # Below variables must be provided for Render deployment.

          # The email address associated with your Render account.
          email: ${{ secrets.RENDER_EMAIL }}

          # Render API key associated with the provided user's email.
          # API Key is available in Render dashboard under Account Settings -> API Keys.
          heroku_api_key: ${{ secrets.RENDER_API_KEY }} # Replace 'heroku_api_key' with 'render_api_key'

          # Name or ID of the Render service to which the build is to be sent.
          # You can find the service ID in your Render dashboard.
          heroku_app_name: ${{ secrets.RENDER_SERVICE_ID }} # Replace 'heroku_app_name' with 'render_service_id'

          # Dockerfile directory (if not in the root, specify the folder path).
          dockerfile_directory: ./

          # Dockerfile name.
          dockerfile_name: Dockerfile

          # Additional Docker options.
          docker_options: "--no-cache"

          # Process type, optional for Render. Defaults to `web`.
          process_type: web
