name: Deploy to Render

# Run the workflow on every push to the develop branch.
on:
  push:
    branches: [develop]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository.
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Install Render CLI
      - name: Install Render CLI
        run: |
          curl -fsSL https://cli.render.com | bash

      # Step 3: Verify Render CLI Installation (Optional Debugging)
      - name: Verify Render CLI Installation
        run: |
          which render
          render --version

      # Step 4: Authenticate with Render
      - name: Authenticate with Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          render login --api-key $RENDER_API_KEY

      # Step 5: Deploy Docker container to Render
      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          render deploy --service-id ${{ secrets.RENDER_SERVICE_ID }}
