name: Deploy to Render

# Run the workflow on every push to the develop branch.
on:
  push:
    branches: [develop]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository.
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t my-app .

      # Step 3: Authenticate with Render (API)
      - name: Authenticate with Render API
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          echo "Using Render API Key: $RENDER_API_KEY"

      # Step 4: Trigger deployment on Render
      - name: Trigger Render Deployment
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          curl -X POST \
            https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploy \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json"
